name: dcase22_t1
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2022.4.26
  - certifi=2022.5.18.1
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.3
  - openssl=1.1.1o
  - pip=21.2.2
  - python=3.7.10
  - readline=8.1.2
  - setuptools=61.2.0
  - sqlite=3.38.3
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - absl-py==1.1.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - appdirs==1.4.4
    - async-timeout==4.0.2
    - asynctest==0.13.0
    - attrs==21.4.0
    - audioread==2.1.9
    - cachetools==5.2.0
    - cffi==1.15.0
    - charset-normalizer==2.0.12
    - colorama==0.4.5
    - cycler==0.11.0
    - decorator==5.1.1
    - docopt==0.6.2
    - einops==0.4.1
    - fonttools==4.33.3
    - frozenlist==1.3.0
    - fsspec==2022.5.0
    - future==0.18.2
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-auth==2.8.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.47.0
    - idna==3.3
    - imageio==2.19.3
    - importlib-metadata==4.11.4
    - joblib==1.1.0
    - jsonpickle==1.5.2
    - kiwisolver==1.4.3
    - librosa==0.9.1
    - llvmlite==0.38.1
    - markdown==3.3.7
    - matplotlib==3.5.2
    - multidict==6.0.2
    - munch==2.5.0
    - numba==0.55.2
    - numpy==1.21.6
    - oauthlib==3.2.0
    - packaging==21.3
    - pandas==1.3.5
    - pillow==9.1.1
    - pooch==1.6.0
    - protobuf==3.19.4
    - py-cpuinfo==8.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.21
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pyyaml==6.0
    - requests==2.28.0
    - requests-oauthlib==1.3.1
    - resampy==0.2.2
    - rsa==4.8
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - six==1.16.0
    - smmap==5.0.0
    - soundfile==0.10.3.post1
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - test-tube==0.7.5
    - threadpoolctl==3.1.0
    - timm==0.4.12
    - torch==1.11.0
    - torchaudio==0.11.0
    - torchinfo==1.7.0
    - torchmetrics==0.2.0
    - torchvision==0.12.0
    - tqdm==4.64.0
    - typing-extensions==4.2.0
    - urllib3==1.26.9
    - werkzeug==2.1.2
    - wrapt==1.14.1
    - yarl==1.7.2
    - zipp==3.8.0

